version: '3.8'
services:
  gnbsim:
      image: gnbsim:latest
      deploy:
        replicas: 3
        restart_policy:
            max_attempts: 3
            condition: on-failure
      env_file:
        - .env
      networks:
        public_net:
          ipv4_address: 192.168.70.156
      healthcheck:
        test: /bin/bash -c "ip address show dev gtp-gnb"
        interval: 10s
        timeout: 5s
        retries: 5

networks:
  public_net:
    driver: overlay
    name: demo-oai-public-net
